"use client";

import { FormEvent, useState } from "react";
import { Button } from "@/components/ui/Button";

const initial = { name: "", email: "", phone: "", company: "", projectType: "", productInterest: "", message: "" };
export function ContactForm() {
  const [form, setForm] = useState(initial); const [status, setStatus] = useState<"idle" | "sending" | "sent" | "error">("idle"); const [message, setMessage] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setStatus("sending"); setMessage(""); try { const response = await fetch("/api/contact", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || "Unable to send your enquiry."); setStatus("sent"); setMessage("Thank you — your enquiry has been received."); setForm(initial); } catch (error) { setStatus("error"); setMessage(error instanceof Error ? error.message : "Unable to send your enquiry."); } }
  const field = "w-full border-b border-ink/25 bg-transparent px-0 py-3 text-sm outline-none transition-colors placeholder:text-muted focus:border-brick";
  return <form onSubmit={submit} className="grid gap-x-8 gap-y-6 sm:grid-cols-2"><label className="text-xs font-medium">Name<input required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} className={field} name="name" placeholder="Your name" /></label><label className="text-xs font-medium">Email<input required type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} className={field} name="email" placeholder="you@company.com" /></label><label className="text-xs font-medium">Phone<input required value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })} className={field} name="phone" placeholder="Phone number" /></label><label className="text-xs font-medium">Company<input required value={form.company} onChange={(e) => setForm({ ...form, company: e.target.value })} className={field} name="company" placeholder="Company / studio" /></label><label className="text-xs font-medium">Project type<select required value={form.projectType} onChange={(e) => setForm({ ...form, projectType: e.target.value })} className={field} name="projectType"><option value="">Select a project type</option><option>Residential</option><option>Commercial / workplace</option><option>Hospitality / retail</option><option>Institutional / civic</option><option>Other</option></select></label><label className="text-xs font-medium">Product interest<select required value={form.productInterest} onChange={(e) => setForm({ ...form, productInterest: e.target.value })} className={field} name="productInterest"><option value="">Select product requirement</option><option>Machine-Made Wire-Cut Red Clay Bricks</option><option>Precision Architectural Red Clay Bricks</option><option>Custom Project Volume Order</option></select></label>
<label className="text-xs font-medium sm:col-span-2">Tell us about the project<textarea required value={form.message} onChange={(e) => setForm({ ...form, message: e.target.value })} className={`${field} min-h-28 resize-y`} name="message" placeholder="Location, stage, intended application, approximate quantity…" /></label><div className="sm:col-span-2"><Button type="submit" className="min-w-44" variant="dark">{status === "sending" ? "Sending" : "Send enquiry"}</Button>{message && <p role="status" className={`mt-4 text-sm ${status === "error" ? "text-red-700" : "text-brick"}`}>{message}</p>}</div></form>;
}
